import { Question } from '../types';

const questions: Question[] = [
  { id: 1, context: "A altura da prancha (x) somada ao tamanho da quilha (y) resulta em 5 unidades. A diferença entre a altura da prancha e o tamanho da quilha é de 1 unidade. Encontre as medidas ideais.", equations: [{ a: 1, b: 1, c: 5 }, { a: 1, b: -1, c: 1 }], solution: { x: 3, y: 2 } },
  { id: 2, context: "O dobro de manobras 'cutback' (x) mais o número de 'aéreos' (y) em uma onda somam 8 pontos. A diferença entre os 'cutbacks' e os 'aéreos' é de 1 ponto. Quantas manobras de cada tipo foram feitas?", equations: [{ a: 2, b: 1, c: 8 }, { a: 1, b: -1, c: 1 }], solution: { x: 3, y: 2 } },
  { id: 3, context: "Um surfista comprou uma parafina (x) e duas raspadores (y) por R$5. Depois, comprou uma parafina (x) e um raspador (y) por R$3. Qual o preço de cada item?", equations: [{ a: 1, b: 2, c: 5 }, { a: 1, b: 1, c: 3 }], solution: { x: 1, y: 2 } },
  { id: 4, context: "O triplo da velocidade do vento (x) menos a altura da onda (y) é 7. A soma da velocidade do vento e da altura da onda é 5. Quais são as condições do mar?", equations: [{ a: 3, b: -1, c: 7 }, { a: 1, b: 1, c: 5 }], solution: { x: 3, y: 2 } },
  { id: 5, context: "Quatro longboards (x) e duas pranchinhas (y) custam juntos R$12. A diferença entre o preço de um longboard e duas pranchinhas é R$3. Qual o valor de cada prancha?", equations: [{ a: 4, b: 2, c: 12 }, { a: 1, b: -2, c: 3 }], solution: { x: 3, y: 0 } },
  { id: 6, context: "A soma de ondas surfadas por Kelly (x) e Gabriel (y) é 6. O dobro das de Kelly menos as de Gabriel é 3.", equations: [{ a: 1, b: 1, c: 6 }, { a: 2, b: -1, c: 3 }], solution: { x: 3, y: 3 } },
  { id: 7, context: "5 vezes a pontuação de Ítalo (x) mais a de Filipe (y) é 7. O dobro da de Ítalo menos a de Filipe é -1.", equations: [{ a: 5, b: 1, c: 7 }, { a: 2, b: -1, c: -1 }], solution: { x: 1, y: 2 } },
  { id: 8, context: "O número de praias visitadas (x) mais o triplo de campeonatos (y) é 10. A diferença entre praias e campeonatos é 2.", equations: [{ a: 1, b: 3, c: 10 }, { a: 1, b: -1, c: 2 }], solution: { x: 4, y: 2 } },
  { id: 9, context: "Duas camisetas (x) e três bermudas (y) de surfe custam R$13. Uma camiseta e uma bermuda custam R$5.", equations: [{ a: 2, b: 3, c: 13 }, { a: 1, b: 1, c: 5 }], solution: { x: 2, y: 3 } },
  { id: 10, context: "A distância percorrida na onda (x) menos o dobro do tempo (y) é -1. O dobro da distância mais o tempo é 8.", equations: [{ a: 1, b: -2, c: -1 }, { a: 2, b: 1, c: 8 }], solution: { x: 3, y: 2 } },
  { id: 11, context: "A temperatura da água (x) e do ar (y) somam 7 graus. A temperatura da água mais o dobro da do ar é 10.", equations: [{ a: 1, b: 1, c: 7 }, { a: 1, b: 2, c: 10 }], solution: { x: 4, y: 3 } },
  { id: 12, context: "Três horas de aula de surfe (x) mais uma hora de aluguel de prancha (y) custam R$9. Uma hora de aula e duas de aluguel custam R$8.", equations: [{ a: 3, b: 1, c: 9 }, { a: 1, b: 2, c: 8 }], solution: { x: 2, y: 3 } },
  { id: 13, context: "O dobro de quilômetros remados (x) menos as calorias queimadas (y, em centenas) é 0. A soma dos dois é 3.", equations: [{ a: 2, b: -1, c: 0 }, { a: 1, b: 1, c: 3 }], solution: { x: 1, y: 2 } },
  { id: 14, context: "A nota em manobras (x) mais o quádruplo da nota em estilo (y) é 9. A diferença entre a nota de manobras e a de estilo é -1.", equations: [{ a: 1, b: 4, c: 9 }, { a: 1, b: -1, c: -1 }], solution: { x: 1, y: 2 } },
  { id: 15, context: "O quádruplo de pranchas vendidas (x) menos as quilhas (y) é 10. O dobro das pranchas mais as quilhas é 8.", equations: [{ a: 4, b: -1, c: 10 }, { a: 2, b: 1, c: 8 }], solution: { x: 3, y: 2 } },
  { id: 16, context: "A soma de surfistas na bateria A (x) e na bateria B (y) é 2. A diferença entre eles é 0.", equations: [{ a: 1, b: 1, c: 2 }, { a: 1, b: -1, c: 0 }], solution: { x: 1, y: 1 } },
  { id: 17, context: "O dobro do preço do leash (x) mais o da cordinha (y) é R$4. A soma dos preços de um de cada é R$3.", equations: [{ a: 2, b: 1, c: 4 }, { a: 1, b: 1, c: 3 }], solution: { x: 1, y: 2 } },
  { id: 18, context: "Na praia, 3 picolés (x) e 2 águas de coco (y) custam R$12. A diferença entre o preço de um picolé e uma água de coco é -R$1.", equations: [{ a: 3, b: 2, c: 12 }, { a: 1, b: -1, c: -1 }], solution: { x: 2, y: 3 } },
  { id: 19, context: "Numa turma de surfe, a quantidade de meninas (x) mais 5 vezes a de meninos (y) é 11. A soma total de alunos é 3.", equations: [{ a: 1, b: 5, c: 11 }, { a: 1, b: 1, c: 3 }], solution: { x: 1, y: 2 } },
  { id: 20, context: "O dobro de fotos tiradas (x) mais o dobro de vídeos (y) é 10. A diferença entre uma foto e o dobro de vídeos é -1.", equations: [{ a: 2, b: 2, c: 10 }, { a: 1, b: -2, c: -1 }], solution: { x: 3, y: 2 } },
  { id: 21, context: "A pontuação de um surfista (x) menos a de outro (y) é -1. O triplo da pontuação do primeiro mais a do segundo é 13.", equations: [{ a: 1, b: -1, c: -1 }, { a: 3, b: 1, c: 13 }], solution: { x: 3, y: 4 } },
  { id: 22, context: "Quatro vezes a duração da onda em segundos (x) mais sua altura em metros (y) é 18. A duração menos a altura é -3.", equations: [{ a: 4, b: 1, c: 18 }, { a: 1, b: -1, c: -3 }], solution: { x: 3, y: 6 } },
  { id: 23, context: "O número de peixes avistados (x) mais o dobro de tartarugas (y) é 8. A soma de peixes e tartarugas é 5.", equations: [{ a: 1, b: 2, c: 8 }, { a: 1, b: 1, c: 5 }], solution: { x: 2, y: 3 } },
  { id: 24, context: "O dobro de horas de treino na água (x) menos o triplo de dias de descanso (y) é -5. A soma de horas e dias é 5.", equations: [{ a: 2, b: -3, c: -5 }, { a: 1, b: 1, c: 5 }], solution: { x: 2, y: 3 } },
  { id: 25, context: "Três sanduíches naturais (x) e um suco (y) na barraca de praia custam R$5. A diferença entre o preço de um sanduíche e um suco é -R$1.", equations: [{ a: 3, b: 1, c: 5 }, { a: 1, b: -1, c: -1 }], solution: { x: 1, y: 2 } },
  { id: 26, context: "O total de pontos de um surfista em duas baterias (x e y) é 10. O dobro dos pontos da primeira menos os da segunda é 5.", equations: [{ a: 1, b: 1, c: 10 }, { a: 2, b: -1, c: 5 }], solution: { x: 5, y: 5 } },
  { id: 27, context: "A altura da maré alta (x) menos o triplo da maré baixa (y) é -5. O dobro da maré alta mais a maré baixa é 12.", equations: [{ a: 1, b: -3, c: -5 }, { a: 2, b: 1, c: 12 }], solution: { x: 5, y: 2 } },
  { id: 28, context: "A soma de quilhas de carbono (x) e de fibra (y) em estoque é 4. O triplo das de carbono menos as de fibra é 4.", equations: [{ a: 1, b: 1, c: 4 }, { a: 3, b: -1, c: 4 }], solution: { x: 2, y: 2 } },
  { id: 29, context: "Cinco camisetas de manga longa (x) e duas de manga curta (y) custam R$14. A diferença de preço entre elas é R$0.", equations: [{ a: 5, b: 2, c: 14 }, { a: 1, b: -1, c: 0 }], solution: { x: 2, y: 2 } },
  { id: 30, context: "O número de ondas para a direita (x) e para a esquerda (y) somam 0. A diferença entre elas é -2.", equations: [{ a: 1, b: 1, c: 0 }, { a: 1, b: -1, c: -2 }], solution: { x: -1, y: 1 } },
  { id: 31, context: "O dobro do preço da lycra (x) mais 5 vezes o da parafina (y) é R$1. A diferença de preço entre uma lycra e uma parafina é R$3.", equations: [{ a: 2, b: 5, c: 1 }, { a: 1, b: -1, c: 3 }], solution: { x: 2, y: -1 } },
  { id: 32, context: "Três bonés (x) menos dois óculos de sol (y) (desconto) custam R$13. Dois bonés mais um óculos custam R$4.", equations: [{ a: 3, b: -2, c: 13 }, { a: 2, b: 1, c: 4 }], solution: { x: 3, y: -2 } },
  { id: 33, context: "A soma da força do vento (x) e da correnteza (y) é 1. O dobro da força do vento menos o triplo da correnteza é 12.", equations: [{ a: 1, b: 1, c: 1 }, { a: 2, b: -3, c: 12 }], solution: { x: 3, y: -2 } },
  { id: 34, context: "Quatro vezes o tamanho do swell (x) mais 3 vezes o período da onda (y) é 10. O dobro do swell menos o período é 12.", equations: [{ a: 4, b: 3, c: 10 }, { a: 2, b: -1, c: 12 }], solution: { x: 4, y: -2 } },
  { id: 35, context: "O número de manobras de borda (x) mais o dobro de manobras no lip (y) é 0. O triplo das de borda menos as do lip é 7.", equations: [{ a: 1, b: 2, c: 0 }, { a: 3, b: -1, c: 7 }], solution: { x: 2, y: -1 } },
  { id: 36, context: "A distância da praia (x) menos a profundidade (y) é 5. O dobro da distância mais o triplo da profundidade é 5.", equations: [{ a: 1, b: -1, c: 5 }, { a: 2, b: 3, c: 5 }], solution: { x: 4, y: -1 } },
  { id: 37, context: "Três vezes a pontuação por velocidade (x) mais a pontuação por estilo (y) é 2. A velocidade menos o dobro do estilo é 3.", equations: [{ a: 3, b: 1, c: 2 }, { a: 1, b: -2, c: 3 }], solution: { x: 1, y: -1 } },
  { id: 38, context: "O dobro de ondas surfadas em Pipeline (x) mais as ondas em Teahupoo (y) soma 7. A diferença entre as ondas nos dois picos é 2.", equations: [{ a: 2, b: 1, c: 7 }, { a: 1, b: -1, c: 2 }], solution: { x: 3, y: 1 } },
  { id: 39, context: "O número de pranchas de um shaper (x) mais o triplo das de outro (y) é 1. O dobro do primeiro mais as do segundo é -3.", equations: [{ a: 1, b: 3, c: 1 }, { a: 2, b: 1, c: -3 }], solution: { x: -2, y: 1 } },
  { id: 40, context: "Quatro ingressos para o campeonato (x) menos uma camiseta (y) custam R$9. Um ingresso mais duas camisetas custam -R$4 (um brinde!).", equations: [{ a: 4, b: -1, c: 9 }, { a: 1, b: 2, c: -4 }], solution: { x: 2, y: -1 } },
  { id: 41, context: "O número de surfistas brasileiros (x) e australianos (y) em uma final soma 1. A diferença entre eles é 3.", equations: [{ a: 1, b: 1, c: 1 }, { a: 1, b: -1, c: 3 }], solution: { x: 2, y: -1 } },
  { id: 42, context: "O dobro de horas de sol (x) mais as horas de vento (y) é 1. Uma hora de sol mais o dobro de vento é 5.", equations: [{ a: 2, b: 1, c: 1 }, { a: 1, b: 2, c: 5 }], solution: { x: -1, y: 3 } },
  { id: 43, context: "Três vezes a temperatura da areia (x) menos a da água (y) é 11. A soma das duas temperaturas é 1.", equations: [{ a: 3, b: -1, c: 11 }, { a: 1, b: 1, c: 1 }], solution: { x: 3, y: -2 } },
  { id: 44, context: "A salinidade da água (x) mais o dobro da umidade do ar (y) é -1. O dobro da salinidade menos a umidade é 3.", equations: [{ a: 1, b: 2, c: -1 }, { a: 2, b: -1, c: 3 }], solution: { x: 1, y: -1 } },
  { id: 45, context: "Para uma viagem, 5 vezes a cotação do dólar (x) mais o preço do euro (y) é 4. O dobro do dólar menos o euro é 5.", equations: [{ a: 5, b: 1, c: 4 }, { a: 2, b: -1, c: 5 }], solution: { x: 1, y: -1 } },
  { id: 46, context: "O número de viagens para a Indonésia (x) menos o dobro de viagens para o Havaí (y) é 7. O dobro para a Indonésia mais uma para o Havaí é 4.", equations: [{ a: 1, b: -2, c: 7 }, { a: 2, b: 1, c: 4 }], solution: { x: 3, y: -2 } },
  { id: 47, context: "O triplo de patrocínios de bebidas (x) mais o dobro de roupas (y) é 0. Um patrocínio de bebida menos um de roupa é -5.", equations: [{ a: 3, b: 2, c: 0 }, { a: 1, b: -1, c: -5 }], solution: { x: -2, y: 3 } },
  { id: 48, context: "O dobro de troféus de ouro (x) menos os de prata (y) é 5. O triplo dos de ouro mais o dobro dos de prata é 4.", equations: [{ a: 2, b: -1, c: 5 }, { a: 3, b: 2, c: 4 }], solution: { x: 2, y: -1 } },
  { id: 49, context: "Numa postagem, os 'likes' (x, em mil) mais 4x os comentários (y, em cem) é -3. O dobro negativo dos 'likes' mais os comentários é 6.", equations: [{ a: 1, b: 4, c: -3 }, { a: -2, b: 1, c: 6 }], solution: { x: -3, y: 0 } },
  { id: 50, context: "Quatro prêmios 'onda do dia' (x) mais um de 'bateria do dia' (y) somam 5 pontos. Uma penalidade de 'onda do dia' (-x) mais dois prêmios de 'bateria do dia' somam 5.", equations: [{ a: 4, b: 1, c: 5 }, { a: -1, b: 2, c: 5 }], solution: { x: 1, y: 1 } },
];


export const getGameQuestions = (): Question[] => {
  const shuffled = [...questions].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, 15);
};